#!/usr/bin/env bash
# Generated by scripts/build-launchers.mjs — do not edit the copy in dist/bin/.
#
# PI WEB runtime launcher (SPEC D1/D2). npm and bun both install package `bin`
# entries as symlinks to this file, so the interpreter cannot be chosen by a
# shebang: it is chosen here, at start, from PI_WEB_RUNTIME, the package manager
# that owns this installation (read from the tree layout — the closest thing to
# a shebang npm and bun can share), and deterministic paths. Service managers
# give their children the *manager* PATH (launchd: /usr/bin:/bin:/usr/sbin:/sbin),
# never the interactive one, which is why discovery also tries fixed candidate
# locations instead of trusting PATH.
set -euo pipefail

TARGET="__TARGET__"
MIN_NODE_VERSION="__MIN_NODE_VERSION__"

# Fixed discovery locations (SPEC D2 step 3), injected at build time so this file stays the only
# copy of the resolution logic: production builds get the real install locations, tests get
# fixture-relative ones. "$HOME" is expanded at start, never at build.
BUN_CANDIDATES=(__BUN_CANDIDATES__)
NODE_CANDIDATES=(__NODE_CANDIDATES__)

SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  case "$SOURCE" in
    /*) ;;
    *) SOURCE="$DIR/$SOURCE" ;;
  esac
done
SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
ENTRY="$SCRIPT_DIR/$TARGET"

# --print-launcher is the installation-identity probe the native-service preflight
# runs before it will exec this file: it answers which package owns the launcher,
# needs no runtime, and validates nothing else, so it must stay ahead of every
# other check.
if [ "${1-}" = "--print-launcher" ]; then
  printf '%s\n' "$SCRIPT_DIR"
  exit 0
fi

# The package manager that installed this tree decides which runtime `auto` prefers —
# the user's package-manager choice is the shebang this file cannot carry. Bun's global
# root is `<root>/install/global/node_modules`; every other layout (npm, pnpm, yarn,
# `bun add -g --linker npm`, dev checkouts) is npm-shaped and prefers Node.js. A missing
# tree degrades to the npm default instead of aborting before the entrypoint error.
PACKAGE_ROOT="$(cd -P "$SCRIPT_DIR/../.." 2>/dev/null && pwd)" || PACKAGE_ROOT=""
case "$PACKAGE_ROOT" in
  */install/global/node_modules|*/install/global/node_modules/*) INSTALLER="bun" ;;
  *) INSTALLER="npm" ;;
esac

# Only the three documented values; an empty value means "not set" = auto.
case "${PI_WEB_RUNTIME-}" in
  ""|auto|bun|node) ;;
  *)
    printf 'pi-web: PI_WEB_RUNTIME=%s is not valid. Use auto, bun or node.\n' "$PI_WEB_RUNTIME" >&2
    exit 2
    ;;
esac

usable_bun() {
  _bun_candidate="$1"
  [ -x "$_bun_candidate" ] || return 1
  # Capability, not version: Bun.Terminal is what drives a PTY without node-pty.
  "$_bun_candidate" -e 'process.exit(typeof Bun.Terminal === "function" ? 0 : 1)' >/dev/null 2>&1
}

usable_node() {
  _node_candidate="$1"
  [ -x "$_node_candidate" ] || return 1
  "$_node_candidate" -e 'const base=(value)=>String(value).split("-")[0].split(".").map(Number);const current=base(process.versions.node);const minimum=base("'$MIN_NODE_VERSION'");for(let i=0;i<Math.max(current.length,minimum.length);i+=1){const left=current[i]??0;const right=minimum[i]??0;if(left>right)break;if(left<right)process.exit(1);}' >/dev/null 2>&1
}

first_usable_bun() {
  for _try in "$@"; do
    if usable_bun "$_try"; then
      printf '%s\n' "$_try"
      return 0
    fi
  done
  return 1
}

first_usable_node() {
  for _try in "$@"; do
    if usable_node "$_try" >/dev/null 2>&1; then
      printf '%s\n' "$_try"
      return 0
    fi
  done
  return 1
}

path_bun() {
  _found="$(command -v bun 2>/dev/null || true)"
  [ -n "$_found" ] || return 1
  printf '%s\n' "$_found"
}

path_node() {
  _found="$(command -v node 2>/dev/null || true)"
  [ -n "$_found" ] || return 1
  printf '%s\n' "$_found"
}

candidate_bun() {
  first_usable_bun "${BUN_CANDIDATES[@]}"
}

candidate_node() {
  first_usable_node "${NODE_CANDIDATES[@]}"
}

# Prints the path of a bun that can boot PI WEB (Bun.Terminal), PATH first, then the fixed
# candidates. Any-bun, capable or not, is separate: a bun that exists but lacks the capability
# is a diagnosable state, not a missing one.
capable_bun() {
  _found="$(path_bun 2>/dev/null || true)"
  if [ -n "$_found" ] && usable_bun "$_found"; then
    printf '%s\n' "$_found"
    return 0
  fi
  first_usable_bun "${BUN_CANDIDATES[@]}"
}

any_bun() {
  _found="$(path_bun 2>/dev/null || true)"
  if [ -n "$_found" ]; then
    printf '%s\n' "$_found"
    return 0
  fi
  for _try in "${BUN_CANDIDATES[@]}"; do
    if [ -x "$_try" ]; then
      printf '%s\n' "$_try"
      return 0
    fi
  done
  return 1
}

# Prints the path of a node that meets the engine floor, PATH first, then the fixed candidates.
capable_node() {
  _found="$(path_node 2>/dev/null || true)"
  if [ -n "$_found" ] && usable_node "$_found"; then
    printf '%s\n' "$_found"
    return 0
  fi
  first_usable_node "${NODE_CANDIDATES[@]}"
}

no_runtime_error() {
  printf 'pi-web: no usable JavaScript runtime found.\n' >&2
  printf '  Looked for bun (with Bun.Terminal) and node >= %s in PATH and the usual install locations.\n' "$MIN_NODE_VERSION" >&2
  printf '  Install one of them, or point PI_WEB_RUNTIME at a runtime: PI_WEB_RUNTIME=bun|node|auto.\n' >&2
  printf '  PI_WEB_RUNTIME is currently %s.\n' "${PI_WEB_RUNTIME:-auto}" >&2
}

# This tree was installed with bun but nothing on the machine can serve it: bun lacks the
# native terminal API and no node meets the floor. Say which bun and how to fix it.
bun_install_no_runtime_error() {
  printf 'pi-web: no usable JavaScript runtime for this bun installation.\n' >&2
  if [ -n "${1-}" ]; then
    printf '  bun was found at %s but it has no Bun.Terminal, and no node >= %s was found in PATH or the usual install locations.\n' "$1" "$MIN_NODE_VERSION" >&2
  else
    printf '  No bun with Bun.Terminal and no node >= %s was found in PATH or the usual install locations.\n' "$MIN_NODE_VERSION" >&2
  fi
  printf '  Fix: run `bun upgrade` (Bun.Terminal needs a current Bun), or install PI WEB with npm to run it on Node.js.\n' >&2
  printf '  PI_WEB_RUNTIME is currently %s.\n' "${PI_WEB_RUNTIME:-auto}" >&2
}

# A bun installation whose only bun lacks Bun.Terminal can still boot PI WEB on Node.js, but the
# node-pty binding that path needs was never built (bun runs dependency install scripts only for
# trusted packages). Warn before starting so the missing terminals are diagnosable.
bun_install_node_fallback_warning() {
  printf 'pi-web: bun at %s has no Bun.Terminal, so PI WEB is starting on Node.js.\n' "$1" >&2
  printf '  Terminals need the node-pty native build: run `bun pm trust node-pty` (reinstall if the binding is still missing), or `bun upgrade` and start again to use Bun PTY.\n' >&2
}

# Echoes "<runtime-kind> <executable>" for the runtime this launch should use.
resolve_runtime() {
  case "${PI_WEB_RUNTIME-}" in
    bun)
      if _exec="$(path_bun)" && usable_bun "$_exec"; then
        printf 'bun %s\n' "$_exec"
        return 0
      fi
      if _exec="$(candidate_bun)"; then
        printf 'bun %s\n' "$_exec"
        return 0
      fi
      printf 'pi-web: PI_WEB_RUNTIME=bun requires bun with Bun.Terminal, but none was found in PATH or the usual install locations.\n' >&2
      return 1
      ;;
    node)
      if _exec="$(path_node)" && usable_node "$_exec"; then
        printf 'node %s\n' "$_exec"
        return 0
      fi
      if _exec="$(candidate_node)"; then
        printf 'node %s\n' "$_exec"
        return 0
      fi
      printf 'pi-web: PI_WEB_RUNTIME=node requires node >= %s, but none was found in PATH or the usual install locations.\n' "$MIN_NODE_VERSION" >&2
      return 1
      ;;
    *)
      if [ "$INSTALLER" = "bun" ]; then
        if _exec="$(capable_bun)"; then
          printf 'bun %s\n' "$_exec"
          return 0
        fi
        if _exec="$(capable_node)"; then
          if _any="$(any_bun)"; then
            bun_install_node_fallback_warning "$_any"
          fi
          printf 'node %s\n' "$_exec"
          return 0
        fi
        _any="$(any_bun)" || _any=""
        bun_install_no_runtime_error "$_any"
        return 1
      fi
      if _exec="$(capable_node)"; then
        printf 'node %s\n' "$_exec"
        return 0
      fi
      if _exec="$(capable_bun)"; then
        printf 'bun %s\n' "$_exec"
        return 0
      fi
      no_runtime_error
      return 127
      ;;
  esac
}

status=0
resolved="$(resolve_runtime)" || status=$?

# --print-runtime is the probe the native-service prerequisite runs: it must
# exit 0 only for a launch that would actually succeed — same capability/floor
# gate AND the same entrypoint check as the real command — so a service and its
# preflight verdict can never disagree.
if [ "$status" -ne 0 ]; then
  exit "$status"
fi

RUNTIME_KIND="${resolved%% *}"
RUNTIME_EXECUTABLE="${resolved#* }"

if [ ! -f "$ENTRY" ] || [ ! -r "$ENTRY" ]; then
  printf 'pi-web: %s entrypoint is missing or unreadable: %s\n' "$RUNTIME_KIND" "$ENTRY" >&2
  exit 127
fi

if [ "${1-}" = "--print-runtime" ]; then
  printf '%s\n' "$RUNTIME_KIND"
  exit 0
fi

exec "$RUNTIME_EXECUTABLE" "$ENTRY" "$@"
