#!/usr/bin/env bash
# Generated by scripts/build-launchers.mjs — do not edit the copy in dist/bin/.
#
# PI WEB runtime launcher (SPEC D1/D2). npm and bun both install package `bin`
# entries as symlinks to this file, so the interpreter cannot be chosen by a
# shebang: it is chosen here, at start, from PI_WEB_RUNTIME and deterministic
# paths. Service managers give their children the *manager* PATH (launchd:
# /usr/bin:/bin:/usr/sbin:/sbin), never the interactive one, which is why
# discovery also tries fixed candidate locations instead of trusting PATH.
set -euo pipefail

TARGET="__TARGET__"
MIN_NODE_VERSION="__MIN_NODE_VERSION__"

SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  case "$SOURCE" in
    /*) ;;
    *) SOURCE="$DIR/$SOURCE" ;;
  esac
done
SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
ENTRY="$SCRIPT_DIR/$TARGET"

# Only the three documented values; an empty value means "not set" = auto.
case "${PI_WEB_RUNTIME-}" in
  ""|auto|bun|node) ;;
  *)
    printf 'pi-web: PI_WEB_RUNTIME=%s is not valid. Use auto, bun or node.\n' "$PI_WEB_RUNTIME" >&2
    exit 2
    ;;
esac

usable_bun() {
  _bun_candidate="$1"
  [ -x "$_bun_candidate" ] || return 1
  # Capability, not version: Bun.Terminal is what drives a PTY without node-pty.
  "$_bun_candidate" -e 'process.exit(typeof Bun.Terminal === "function" ? 0 : 1)' >/dev/null 2>&1
}

usable_node() {
  _node_candidate="$1"
  [ -x "$_node_candidate" ] || return 1
  "$_node_candidate" -e 'const base=(value)=>String(value).split("-")[0].split(".").map(Number);const current=base(process.versions.node);const minimum=base("'$MIN_NODE_VERSION'");for(let i=0;i<Math.max(current.length,minimum.length);i+=1){const left=current[i]??0;const right=minimum[i]??0;if(left>right)break;if(left<right)process.exit(1);}' >/dev/null 2>&1
}

first_usable_bun() {
  for _try in "$@"; do
    if usable_bun "$_try"; then
      printf '%s\n' "$_try"
      return 0
    fi
  done
  return 1
}

first_usable_node() {
  for _try in "$@"; do
    if usable_node "$_try" >/dev/null 2>&1; then
      printf '%s\n' "$_try"
      return 0
    fi
  done
  return 1
}

path_bun() {
  _found="$(command -v bun 2>/dev/null || true)"
  [ -n "$_found" ] || return 1
  printf '%s\n' "$_found"
}

path_node() {
  _found="$(command -v node 2>/dev/null || true)"
  [ -n "$_found" ] || return 1
  printf '%s\n' "$_found"
}

candidate_bun() {
  first_usable_bun "$HOME/.bun/bin/bun" /usr/local/bin/bun /opt/homebrew/bin/bun /usr/bin/bun
}

candidate_node() {
  first_usable_node /usr/bin/node /usr/local/bin/node /opt/homebrew/bin/node
}

no_runtime_error() {
  printf 'pi-web: no usable JavaScript runtime found.\n' >&2
  printf '  Looked for bun (with Bun.Terminal) and node >= %s in PATH and the usual install locations.\n' "$MIN_NODE_VERSION" >&2
  printf '  Install one of them, or point PI_WEB_RUNTIME at a runtime: PI_WEB_RUNTIME=bun|node|auto.\n' >&2
  printf '  PI_WEB_RUNTIME is currently %s.\n' "${PI_WEB_RUNTIME:-auto}" >&2
}

# Echoes "<runtime-kind> <executable>" for the runtime this launch should use.
resolve_runtime() {
  case "${PI_WEB_RUNTIME-}" in
    bun)
      if _exec="$(path_bun)" && usable_bun "$_exec"; then
        printf 'bun %s\n' "$_exec"
        return 0
      fi
      if _exec="$(candidate_bun)"; then
        printf 'bun %s\n' "$_exec"
        return 0
      fi
      printf 'pi-web: PI_WEB_RUNTIME=bun requires bun with Bun.Terminal, but none was found in PATH or the usual install locations.\n' >&2
      return 1
      ;;
    node)
      if _exec="$(path_node)" && usable_node "$_exec"; then
        printf 'node %s\n' "$_exec"
        return 0
      fi
      if _exec="$(candidate_node)"; then
        printf 'node %s\n' "$_exec"
        return 0
      fi
      printf 'pi-web: PI_WEB_RUNTIME=node requires node >= %s, but none was found in PATH or the usual install locations.\n' "$MIN_NODE_VERSION" >&2
      return 1
      ;;
    *)
      if _exec="$(path_bun)" && usable_bun "$_exec"; then
        printf 'bun %s\n' "$_exec"
        return 0
      fi
      if _exec="$(candidate_bun)"; then
        printf 'bun %s\n' "$_exec"
        return 0
      fi
      if _exec="$(path_node)" && usable_node "$_exec"; then
        printf 'node %s\n' "$_exec"
        return 0
      fi
      if _exec="$(candidate_node)"; then
        printf 'node %s\n' "$_exec"
        return 0
      fi
      no_runtime_error
      return 127
      ;;
  esac
}

status=0
resolved="$(resolve_runtime)" || status=$?

# --print-runtime is the probe the native-service prerequisite runs: it must
# exit 0 only for a runtime that passed the capability/floor gate, never reach
# the JavaScript entrypoint, and report the same status the real command would
# (127 when nothing is usable) so the probe and the service agree.
if [ "$status" -ne 0 ]; then
  exit "$status"
fi

if [ "${1-}" = "--print-runtime" ]; then
  printf '%s\n' "${resolved%% *}"
  exit 0
fi

RUNTIME_KIND="${resolved%% *}"
RUNTIME_EXECUTABLE="${resolved#* }"

if [ ! -f "$ENTRY" ]; then
  printf 'pi-web: %s entrypoint is missing: %s\n' "$RUNTIME_KIND" "$ENTRY" >&2
  exit 127
fi

exec "$RUNTIME_EXECUTABLE" "$ENTRY" "$@"
