import type { PiWebPlugin, ThemeTokens } from "../types";

const classicTokens = {
  "--pi-bg": "#0d1117",
  "--pi-surface": "#161b22",
  "--pi-surface-hover": "#21262d",
  "--pi-terminal-bg": "#05070a",
  "--pi-terminal-text": "#e6edf3",
  "--pi-border": "#30363d",
  "--pi-border-muted": "#21262d",
  "--pi-text": "#e6edf3",
  "--pi-text-secondary": "#c9d1d9",
  "--pi-text-bright": "#f0f6fc",
  "--pi-muted": "#8b949e",
  "--pi-dim": "#6e7681",
  "--pi-accent": "#58a6ff",
  "--pi-accent-border": "#2f81f7",
  "--pi-selection-bg": "#0d2847",
  "--pi-success": "#3fb950",
  "--pi-success-border": "#238636",
  "--pi-success-bg": "#0f1b12",
  "--pi-success-surface": "#0f2a16",
  "--pi-success-ring": "#3fb95055",
  "--pi-warning": "#d29922",
  "--pi-warning-border": "#6e5200",
  "--pi-warning-surface": "#1f1a10",
  "--pi-danger": "#ff7b72",
  "--pi-purple": "#d2a8ff",
  "--pi-purple-border": "#a371f7",
  "--pi-purple-surface": "#21132f",
  "--pi-overlay": "#0008",
  "--pi-shadow-soft": "#0006",
  "--pi-shadow": "#0008",
  "--pi-shadow-strong": "#000b",
  "--pi-bg-overlay-soft": "#0d1117dd",
  "--pi-bg-overlay": "#0d1117e6",
  "--pi-success-bg-overlay": "#0f1b12ee",
  "--pi-terminal-selection": "#264f78",
} satisfies ThemeTokens;

const piWebDarkTokens = {
  "--pi-bg": "#1e1e2e",
  "--pi-surface": "#313244",
  "--pi-surface-hover": "#45475a",
  "--pi-terminal-bg": "#11111b",
  "--pi-terminal-text": "#cdd6f4",
  "--pi-border": "#585b70",
  "--pi-border-muted": "#45475a",
  "--pi-text": "#cdd6f4",
  "--pi-text-secondary": "#bac2de",
  "--pi-text-bright": "#cdd6f4",
  "--pi-muted": "#a6adc8",
  "--pi-dim": "#7f849c",
  "--pi-accent": "#cba6f7",
  "--pi-accent-border": "#8670a7",
  "--pi-selection-bg": "#3d3752",
  "--pi-success": "#a6e3a1",
  "--pi-success-border": "#709473",
  "--pi-success-bg": "#2c323a",
  "--pi-success-surface": "#374243",
  "--pi-success-ring": "#a6e3a155",
  "--pi-warning": "#f9e2af",
  "--pi-warning-border": "#978a75",
  "--pi-warning-surface": "#3d3940",
  "--pi-danger": "#f38ba8",
  "--pi-purple": "#b4befe",
  "--pi-purple-border": "#787eab",
  "--pi-purple-surface": "#36384f",
  "--pi-overlay": "#11111baa",
  "--pi-shadow-soft": "#11111b66",
  "--pi-shadow": "#11111b99",
  "--pi-shadow-strong": "#11111bcc",
  "--pi-bg-overlay-soft": "#1e1e2edd",
  "--pi-bg-overlay": "#1e1e2ee6",
  "--pi-success-bg-overlay": "#2c323aee",
  "--pi-terminal-selection": "#585b70",
} satisfies ThemeTokens;

const piWebLightTokens = {
  "--pi-bg": "#eff1f5",
  "--pi-surface": "#e6e9ef",
  "--pi-surface-hover": "#dce0e8",
  "--pi-terminal-bg": "#1e1e2e",
  "--pi-terminal-text": "#cdd6f4",
  "--pi-border": "#bcc0cc",
  "--pi-border-muted": "#ccd0da",
  "--pi-text": "#4c4f69",
  "--pi-text-secondary": "#5c5f77",
  "--pi-text-bright": "#4c4f69",
  "--pi-muted": "#6c6f85",
  "--pi-dim": "#7c7f93",
  "--pi-accent": "#8839ef",
  "--pi-accent-border": "#8839ef",
  "--pi-selection-bg": "#e1d7f4",
  "--pi-success": "#40a02b",
  "--pi-success-border": "#40a02b",
  "--pi-success-bg": "#dde9e1",
  "--pi-success-surface": "#d0e2d1",
  "--pi-success-ring": "#40a02b55",
  "--pi-warning": "#df8e1d",
  "--pi-warning-border": "#df8e1d",
  "--pi-warning-surface": "#ede1d2",
  "--pi-danger": "#d20f39",
  "--pi-purple": "#7287fd",
  "--pi-purple-border": "#7287fd",
  "--pi-purple-surface": "#e0e5fb",
  "--pi-overlay": "#4c4f6966",
  "--pi-shadow-soft": "#4c4f6922",
  "--pi-shadow": "#4c4f6933",
  "--pi-shadow-strong": "#4c4f6944",
  "--pi-bg-overlay-soft": "#eff1f5dd",
  "--pi-bg-overlay": "#eff1f5e6",
  "--pi-success-bg-overlay": "#dde9e1ee",
  "--pi-terminal-selection": "#585b70",
} satisfies ThemeTokens;

export const themePackPlugin: PiWebPlugin = {
  apiVersion: 2,
  name: "PI WEB Themes",
  activate: () => ({
    contributions: {
      themes: [
        {
          id: "pi-web-dark",
          name: "PI WEB Dark",
          description: "Catppuccin Mocha palette.",
          order: 10,
          colorScheme: "dark",
          tokens: piWebDarkTokens,
        },
        {
          id: "pi-web-light",
          name: "PI WEB Light",
          description: "Catppuccin Latte palette.",
          order: 20,
          colorScheme: "light",
          tokens: piWebLightTokens,
        },
        {
          id: "classic",
          name: "PI WEB Classic",
          description: "The original PI WEB dark palette.",
          order: 30,
          colorScheme: "dark",
          tokens: classicTokens,
        },
      ],
      themePairs: [
        {
          id: "pi-web",
          name: "PI WEB",
          description: "Follow the system light/dark preference with PI WEB themes.",
          order: 10,
          light: "pi-web-light",
          dark: "pi-web-dark",
        },
      ],
    },
  }),
};
